services:

  prometheus:
    extends:
        file: docker-base-services/base-compose-services-observability.yml
        service: prometheus-base
    volumes:
      - "${pwd-.}/observability/prom/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "${pwd-.}/.data/.prometheus:/prometheus"
        
  grafana:
    extends:
        file: docker-base-services/base-compose-services-observability.yml
        service: grafana-base
    volumes:
      - "${pwd-.}/observability/grafana/custom.ini:/usr/share/grafana/conf/defaults.ini:ro"
      - "${pwd-.}/observability/grafana/provisioning/:/etc/grafana/provisioning"
      - "${pwd-.}/observability/data/grafana:/var/lib/grafana"
    depends_on:
      - prometheus
