services:

  redpanda-0:
    extends:
        file: docker-base-services/base-compose-services-messaging.yml
        service: redpanda
    container_name: redpanda-0
    volumes:
      - ./.data/.kafka:/var/lib/redpanda/data
    networks:
      - redpanda_network
        
  redpanda-console:
    extends:
        file: docker-base-services/base-compose-services-messaging.yml
        service: redpanda-console
    container_name: redpanda-console
    networks:
      - redpanda_network
    depends_on:
      - redpanda-0
        
networks:
  redpanda_network:
    driver: bridge
