entryPoints:
  web:
    address: :8200
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 1
        graceTimeOut: 5
  traefik:
    address: :8089

providers:
  file:
    directory: .
    watch: true

accessLog: {}

log:
 level: DEBUG

api:
  # Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard: true
  insecure: true
